### ISSUE TITLE
Wrong RSS links

### ISSUE THREAD

**Issue by ForNeVeR** [rexim/rexim.me#6]
Hello meester, it seems that your RSS is broken. Look, you have [the following](http://rexim.me/rss.xml):

```xml
<guid>http://rexim.me/emacs-home-for-windows</guid>
```

According to the [RSS 2.0 spec][rss],
> If the guid element has an attribute named "isPermaLink" with a value of true, the reader may assume that it is a permalink to the item, that is, a url that can be opened in a Web browser, that points to the full item described by the <item> element.
> [...]
> isPermaLink is optional, its default value is true.

(And yeah, that's a *strange* aspect, but that is the spec after all, and we're here not to discuss it.)

But the text inside your `<guid>` element is not a proper link to the post content - real link contains the `.html` extension.

I have noticed this problem today when I wanted to read about your emacs thing using a link from my RSS reader.

Pleese fix that!

[rss]: http://cyber.law.harvard.edu/rss/rss.html

**Comment by rexim** [comment]
Thanks, dr. von Never! I'll fix that ASAP!
